mod ayu_dark;
mod catppuccin;
mod dracula;
mod everforest;
mod github_dark;
mod gruvbox;
mod material;
mod monokai;
mod night_owl;
mod nord;
mod one_dark;
mod rose_pine;
mod solarized_dark;
mod solarized_light;
mod telemetry;
mod tokyo_night;

pub use ayu_dark::ayu_dark;
pub use catppuccin::catppuccin;
pub use dracula::dracula;
pub use everforest::everforest;
pub use github_dark::github_dark;
pub use gruvbox::gruvbox;
pub use material::material;
pub use monokai::monokai;
pub use night_owl::night_owl;
pub use nord::nord;
pub use one_dark::one_dark;
pub use rose_pine::rose_pine;
pub use solarized_dark::solarized_dark;
pub use solarized_light::solarized_light;
pub use telemetry::telemetry;
pub use tokyo_night::tokyo_night;
